export const data=[
    {
        id:1,
        "title":"kathakali",
        "details":"Kathakali ( IAST: Kathakaḷi Malayalam: കതകളി) is a major form of classical Indian dance.[1] It is a story play genre of art, but one distinguished by the elaborately colourful make-up and costumes of the traditional male actor-dancers.",
        "image":"img5.jpg",
        desc2:"Kathakali ( IAST: Kathakaḷi Malayalam: കതകളി) is a major form of classical Indian dance.[1] It is a story play genre of art, but one distinguished by the elaborately colourful make-up and costumes of the traditional male actor-dancers.[2][3][note 1] It is native to the Malayalam-speaking southwestern region of Kerala and is almost entirely practiced and appreciated by Malayali people Kathakali's roots are unclear. The fully developed style of Kathakali originated around the 17th century, but its roots are in the temple and folk arts (such as Krishnanattam and religious drama of the kingdom of the Zamorin of Calicut) southwestern Indian peninsula), which are traceable to at least the 1st millennium CE.[2][6] A Kathakali performance, like all classical dance arts of India, synthesizes music, vocal performers, choreography and hand and facial gestures together to express ideas. However, Kathakali differs in that it also incorporates movements from ancient Indian martial arts and athletic traditions of South India.) [2][3][5] Kathakali also differs in that the structure and details of its art form developed in the courts and theatres of Hindu principalities, unlike other classical Indian dances which primarily developed in Hindu temples and monastic schools.The traditional themes of the Kathakali are folk stories, religious legends and spiritual ideas from the Hindu epics and the Puranas.[7] The vocal performance has traditionally been performed in Sanskritised Malayalam.[6] In modern compositions, Indian Kathakali troupes have included women artistes,[4] and adapted Western stories and plays such as those by Shakespeare",
    },
    {
        id:2,
        "title":"mohiniyattam",
        "details":"Mohiniyattam, (Malayalam: മോഹിനിയാട്ടം), is an Indian classical dance form that developed and remained popular in the state of Kerala.[1][2] Kathakali is another classical dance form of Kerala.[3][4] Mohiniyattam dance gets its name.............",
        "image":"img6.jpg",
        desc2:"Mohiniyattam, (Malayalam: മോഹിനിയാട്ടം), is an Indian classical dance form that developed and remained popular in the state of Kerala.[1][2] Kathakali is another classical dance form of Kerala.[3][4] Mohiniyattam dance gets its name from the word Mohini  a historical enchantress avatar of the Hindu God Vishnu, who helps the good prevail over evil by developing her feminine powers.Mohiniyattam's roots, like all classical Indian dances, are in the Natya Shastra – the ancient Hindu Sanskrit text on performance arts.[6][7] However, it follows the Lasya style described in Natya Shastra, that is a dance which is delicate, eros-filled and feminine.[2][8] It is traditionally a solo dance performed by women after extensive training, though nowadays men can also perform the dance.[9][10][11][12] The repertoire of Mohiniyattam includes music in the Carnatic style, singing and acting a play through the dance, where the recitation may be either by a separate vocalist or the dancer themselves.The earliest mention of the word is found in the 16th-century legal text Vyavaharamala, but the likely roots of the dance are older.[13] The dance was systematized in the 18th century, was ridiculed as a Devadasi prostitution system during the colonial British Raj, banned by a series of laws from 1931 through 1938, a ban that was protested and partially repealed in 1940.[14] The socio-political conflict ultimately led to renewed interest, revival and reconstruction of Mohiniyattam by the people of Kerala, particularly the poet Vallathol Narayana Menon"
    },
    {
        id:3,
        "title":"Bharatanatyam ",
        "details":"Bharatanatyam (Tamil: பரதநாட்டியம்) is a major form of Indian classical dance that originated in Tamil Nadu.[1][2] It is one of the eight widely recognized Indian classical dance forms, and expresses South Indian religious themes and spiritual ideas,",
        "image":"img2.jpg",
        desc2:"Bharatanatyam, a pre-eminent Indian classical dance form presumably the oldest classical dance heritage of India is regarded as mother of many other Indian classical dance forms. Conventionally a solo dance performed only by women, it initiated in the Hindu temples of Tamil Nadu and eventually flourished in South India. Theoretical base of this form traces back to ‘Natya Shastra’, the ancient Sanskrit Hindu text on the performing arts. A form of illustrative anecdote of Hindu religious themes and spiritual ideas emoted by dancer with excellent footwork and impressive gestures its performance repertoire includes nrita, nritya and natya. Accompanists include a singer, music and particularly the guru who directs and conducts the performance. It also continues to inspire several art forms including paintings and sculptures starting from the spectacular 6th to 9th century CE temple sculptures. According to the Hindu tradition the name of the dance form was derived by joining two words, ‘Bharata’ and Natyam’ where ‘Natyam in Sanskrit means dance and ‘Bharata’ is a mnemonic comprising ‘bha’, ‘ra’ and ‘ta’ which respectively means ‘bhava’ that is emotion and feelings; ‘raga’ that is melody; and ‘tala’ that is rhythm. Thus, traditionally the word refers to a dance form where bhava, raga and tala are expressed. The theoretical base of this dance form, which is also referred as Sadir, trace back to ancient Indian theatrologist and musicologist, Bharata Muni’s Sanskrit Hindu text on the performing arts called ‘Natya Shastra’. The text’s first complete version was presumably completed between 200 BCE to 200 CE, however such timeframe also varies between 500 BCE and 500 CE. According to legends Lord Brahma revealed Bharatanatyam to the sage Bharata who then encoded this holy dance form in Natya Shastra. The text that consists of thousands of verses structured in different chapters divides dance in two specific forms, namely ‘nrita’ that is pure dance comprising of finesse of hand movements and gestures, and nritya that is solo expressive dance that comprises of expressions. According to Russian scholar Natalia Lidova, ‘Natya Shastra’ elucidates several theories of Indian classical dances including that of Tandava dance, standing postures, basic steps, bhava, rasa, methods of acting and gestures.Theyyam season starts from the tenth day of the Malayalam month of Thulam (usually falls during October, and known as paththaam-udayam) and lasts up to seven months till the middle of Edavam month (typically around May end, June). The last Kaliyaattam for the season is performed at Madayi Kavu and Kalarivathukkal Bhagavathy Temple, Both being the family shrines of Kolathiri royal family."
    },
    {
        id:4,
        "title":"Theyyam",
        "details":"Theyyam are Hindu ritualistic dance forms practiced in northern Kerala and some parts of Karnataka. Theyyam is also known as Kaḷiyāṭṭaṁ or Tiṟa. Theyyam consists of traditions, rituals and customs associated with temples and sacred groves of Malabar",
        "image":"theyyam.jpg",
        desc2:"Theyyam (/; romanised: teyyam) are Hindu ritualistic dance forms practiced in northern Kerala and some parts of Karnataka. Theyyam is also known as Kaḷiyāṭṭaṁ or Tiṟa. Theyyam consists of traditions, rituals and customs associated with temples and sacred groves of Malabar.[1] The people of the region consider Theyyam itself as a channel to a god and they thus seek blessings from Theyyam.Theyyam is typically performed by people from castes and tribes like Pulayar, Vannan, Malayan, Anhoottan, Munnoottan, Mavilan, Koppalan, Velan, Chingathan, Kalanaadi, Paravan, Nalikeyavar etc. Of these Kalanaadi people perform only in Wayanad district, while Parava, Pampatha, Nalikeyavar perform in places north of Kerala like Udupi, Krishnapuram etc.Theyyam season starts from the tenth day of the Malayalam month of Thulam (usually falls during October, and known as paththaam-udayam) and lasts up to seven months till the middle of Edavam month (typically around May end, June). The last Kaliyaattam for the season is performed at Madayi Kavu and Kalarivathukkal Bhagavathy Temple, Both being the family shrines of Kolathiri royal family."
    },
    {
        id:5,
        "title":"Yakshagana",
        "details":"Yakshagaana is a traditional theatre, developed in Dakshina Kannada, Udupi, Uttara Kannada, Shimoga and western parts of Chikmagalur districts, in the state of Karnataka and in Kasaragod district in Kerala that combines dance, music, dialogue, costume, make-up........................",
        "image":"yakshaganam.jpg",
        desc2:"Yakshagana literally means the people (gana) who are the yaksha (nature spirits).[5] Yakshagana is the scholastic name in Kannada (used for the last 200 years) for art forms formerly known as kēḷike, āṭa, bayalāṭa, and daśāvatāra. The word Yakshagana previously referred to a form of literature primarily in Kannada (starting from the 16th century). Of late Yakshaganas in Tulu and even now in Telugu are available. Performance of this Yakshagana literature or the play is called āṭa. It is now no longer believedYakshagaana is a traditional theatre, developed in Dakshina Kannada, Udupi, Uttara Kannada, Shimoga and western parts of Chikmagalur districts, in the state of Karnataka and in Kasaragod district in Kerala that combines dance, music, dialogue, costume, make-up, and stage techniques with a unique style and form. It is believed to have evolved from pre-classical music and theatre during the period of the Bhakti movement.[1] It is sometimes simply called Aata or āṭa (meaning the play).[2] This theatre style is mainly found in coastal regions of Karnataka in various forms. Towards the south from Dakshina Kannada to Kasaragod of Tulu Nadu region, the form of Yakshagana is called Thenku thittu and towards the north from Udupi up to Uttara Kannada it is called Badaga thittu. Both of these forms are equally played all over the region.(Not sure about this one but) Yakshagana is traditionally presented from dusk to dawn. Its stories are drawn from Ramayana, Mahabharata, Bhagavata and other epics from both Hindu and Jain and other ancient Indic traditions that the word Ekkalagaana refers to Yakshagana."
    },
   
    {
        id:6,
        "title":"Odissi",
        "details":"Odissi (Odia: ଓଡ଼ିଶୀ), also referred to as Orissi in old literature, is a major ancient Indian classical dance that originated in the temples of Odisha – an eastern coastal state of India.[1][2][3] Odissi, in its history, was performed predominantly by women,[1][4] and expressed religious stories and spirital ideas.",
        "image":"odissi.jpg",
        desc2:"Odissi (Odia: ଓଡ଼ିଶୀ), also referred to as Orissi in old literature, is a major ancient Indian classical dance that originated in the temples of Odisha – an eastern coastal state of India.[1][2][3] Odissi, in its history, was performed predominantly by women,[1][4] and expressed religious stories and spirital ideas, particularly of Vaishnavism through songs written and composed according to the ragas & talas of Odissi music by ancient poets of the state. Odissi performances have also expressed ideas of other traditions such as those related to Hindu Gods Shiva and Surya, as well as Hindu Goddesses (Shaktism).[5] The theoretical foundations of Odissi trace to the ancient Sanskrit text Natya Shastra, its existence in antiquity evidenced by the dance poses in the sculptures of Kalingan temples,[1][6] and archeological sites related to Hinduism (Sanatana Dharma), Buddhism and Jainism.[7][8][9] It was suppressed under the British Rule.[10][11] The suppression was protested by the Indians, followed by its revival, reconstruction and expansion since India gained independence from the colonial rule.Odissi is traditionally a dance-drama genre of performance art, where the artist(s) and musicians play out a story, a spiritual message or devotional poem from the Hindu texts, using symbolic costumes,[12] body movement, abhinaya (expressions) and mudras (gestures and sign language) set out in ancient Sanskrit literature.[13] Classical Odia literature & the Gita Govinda set to traditional Odissi music are used for the abhinaya. Odissi is learnt and performed as a composite of basic dance motif called the Bhangas (symmetric body bends, stance). It involves lower (footwork), mid (torso) and upper (hand and head) as three sources of perfecting expression and audience engagement with geometric symmetry and rhythmic musical resonance.[14][15] An Odissi performance repertoire includes invocation, nritta (pure dance), nritya (expressive dance), natya (dance drama) and moksha (dance climax connoting freedom of the soul and spiritual release)."
    },
    {
        id:7,
        "title":"kalaripayattu",
        "details":"Kalaripayattu (IPA: [kɐɭɐɾip:ɐjɐt:ɨ̆]; also known simply as Kalari) is an Indian martial art that originated in modern-day Kerala, a state on the southwestern coast of India.[5][6][7] Kalaripayattu is known for its long-standing history within Indian martial arts, and is one of the oldest surviving martial arts in India.",
        "image":"kalari.jpg",
        desc2:"Kalaripayattu (IPA: [kɐɭɐɾip:ɐjɐt:ɨ̆]; also known simply as Kalari) is an Indian martial art that originated in modern-day Kerala, a state on the southwestern coast of India.[5][6][7] Kalaripayattu is known for its long-standing history within Indian martial arts, and is one of the oldest surviving martial arts in India.Like most Indian martial arts, Kalaripayattu contains rituals and philosophies inspired by Hinduism.[11] The art also bases medical treatments upon concepts found in the ancient Indian medical text, the Ayurveda.[5][9] Practitioners of Kalaripayattu possess intricate knowledge of pressure points on the human body and healing techniques that incorporate the knowledge of Ayurveda and Yoga.[12] Kalaripayattu is taught in accordance with the Indian guru-shishya system.[13] Kalaripayattu differs from many other martial arts systems in the world in that weapon based techniques are taught first, and barehanded techniques are taught last.Elements from the yoga tradition as well as finger movements in the nata dances, were incorporated into Kalaripayattu.[15] A number of South Asian fighting styles remain closely connected to yoga, dance and performing arts. Some of the choreographed sparring in Kalaripayattu can be applied to dance[16] and Kathakali dancers who knew Kalaripayattu were believed to be markedly better than other performers. Some traditional Indian classical dance schools still incorporate martial arts as part of their exercise regimen."
    },
    {
        id:8,
        "title":"Madhubani Art",
        "details":"This art is also known as Mithila art, and it originated in the kingdom of Janak in Nepal and in present-day Bihar. This art form was not known to the rest of the world until the 1930s, when it was discovered after an earthquake.The paint is created using natural dyes and pigments........ .",
        "image":"mad.jpg",
        desc2:"Mithila painting is a style of painting practiced in the Mithila region of India and Nepal. Artists create these paintings using a variety of mediums, including their own fingers, or twigs, brushes, nib-pens, and matchstick. The paint is created using natural dyes and pigments. The paintings are characterised by their eye-catching geometrical patterns. There is ritual content for particular occasions, such as birth or marriage, and festivals, such as Holi, Surya Shasti, Kali Puja, Upanayana, and Durga Puja.Madhubani painting (Mithila painting) was traditionally created by the women of various communities in the Mithila region of the Indian subcontinent. It originated from Madhubani district of the Mithila region of Bihar. Madhubani is also a major export center of these paintings.[1] This painting as a form of wall art was practiced widely throughout the region; the more recent development of painting on paper and canvas mainly originated among the villages around Madhubani, and it is these latter developments that led to the term Madhubani art being used alongside Mithila Painting.The paintings were traditionally done on freshly plastered mud walls and floors of huts, but now they are also done on cloth, handmade paper and canvas.[3] Madhubani paintings are made from the paste of powdered rice. Madhubani painting has remained confined to a compact geographical area and the skills have been passed on through centuries, the content and the style have largely remained the same. Thus, Madhubani painting has received GI (Geographical Indication) status. Madhubani paintings use two-dimensional imagery, and the colors used are derived from plants. Ochre, Lampblack and Red are used for reddish-brown and black, respectively."
    },
  
]
